# Numpy Fundamentals

### Numpy is the fundamental package for scientific computing in python. It is a python library that provides a Multi dimensional Array object and various derived objects Masked Arrays or Matrices and an assortment of routine for fast operations on Arrays including Mathematical , Logical , Shape Manipulation , Sorting , Selecting , I/O , Discrete Fourier Transform , Basic Liner Algebra , Statistical Operation , Random Simulation , etc.

### At the core the Numpy Package is the n-dimensional Array Object.

## Numpy Arrays VS Python Sequences

### Numpy Arrays have a fixed size at creation , unlike Python Lists which grow dynamically. Changing the size of an nd array will create the new array and delete the origin al array.

### The element of the Numpy Array are required to be the same data type and thus will be the same size in the memory.

### Numpy Arrays facilitate advanced Mathematical and other types of Operations on large number of Data . Typically , such operations are executed more efficiently with less code than is possible using Python's built in sequences.

In [1]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 2.5 MB/s eta 0:00:0000:0100:010m
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
print("Numpy Version : " ,np.__version__)

Numpy Version :  2.4.6


In [4]:
numpy_array = np.array([1,2,3,4,5])
numpy_array

array([1, 2, 3, 4, 5])

In [6]:
type(numpy_array)

numpy.ndarray

In [7]:
twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
twoD_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
threeD_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
threeD_array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## dtype parameter ----->  which can help to decide about the size of the data inside the array.

In [10]:
np.array([1,2,3,4,5], dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [11]:
np.array([1,2,3,4,5], dtype=np.int64)

array([1, 2, 3, 4, 5])

In [14]:
np.arange(3 , 20, 3)

array([ 3,  6,  9, 12, 15, 18])

In [16]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])